name = "worker-searcher-cf"
type = "javascript"
account_id = "45a3cb295383bc335b87b00ecd51ab9e56b2e"
workers_dev = true

[site]
bucket = "your-bucket-name"
entry-point = "workers-site"

[build]
command = "node server.js"