name = "worker-searcher-cf"
account_id = "40b7018d3702a1b9d2ab26e35bc49475"
compatibility_date = "2023-05-19"
main = "src/index.cjs"
workers_dev = true

[site]
bucket = "88563dc09c0a47ecbc40ec5a357d8526"

[build]
command = "npm run build"

kv_namespaces = [
  { binding = "__STATIC_CONTENT", id = "88563dc09c0a47ecbc40ec5a357d8526" }
]