name: IndexNow

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]

jobs:
  submit-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: IndexNow
        uses: jakob-bagterp/index-now-submit-sitemap-urls-action@v1
        with:
          host: csgobroker.cc
          api_key: ${{ secrets.INDEX_NOW_API_KEY }}
          api_key_location: https://csgobroker.cc/${{ secrets.INDEX_NOW_API_KEY }}.txt
          endpoint: indexnow
          sitemap_locations: >
            https://csgobroker.cc/sitemap_main.xml
            https://csgobroker.cc/sitemap_main_ru.xml
            https://csgobroker.cc/sitemap_reviews.xml
            https://csgobroker.cc/sitemap_reviews_ru.xml
            https://csgobroker.cc/sitemap_reviews_es.xml
            https://csgobroker.cc/sitemap_topics.xml
            https://csgobroker.cc/sitemap_topics_ru.xml
